# SPDX-FileCopyrightText: Copyright (c) CloudZero, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
costformation

A Python library for defining CostFormation dimensions as classes and generating YAML output.
Supports building dimensions with rules using Python expressions.
"""

from costformation.allocations import (
    AllocationMethod,
    CostType,
    ElementCutoff,
    FixedRate,
    Granularity,
    ProportionalMethod,
)
from costformation.conditions import (
    After,
    AfterOrEquals,
    And,
    Before,
    BeforeOrEquals,
    BeginsWith,
    Condition,
    Contains,
    EndsWith,
    Equals,
    ForDateRange,
    HasValue,
    Matches,
    Not,
    Or,
)
from costformation.core_dimensions import (
    Account,
    BillingConnectionID,
    CloudProvider,
    CommittedUseSubscription,
    Description,
    InvoiceID,
    K8s_Cluster,
    K8s_Label,
    K8s_Namespace,
    K8s_Workload,
    LineItemType,
    Operation,
    PayerAccount,
    PricingTerm,
    PricingUnit,
    PricingUnits,
    ProductFamily,
    Region,
    RequestType,
    Resource,
    Service,
    Tag,
    TransferType,
    UsageDay,
    UsageFamily,
    UsageType,
)
from costformation.dimensions import (
    AcrossElements,
    AllocationDimension,
    CoreDimension,
    CostFormation,
    Dimension,
    ForEachElementOf,
    GlobalDimension,
    GroupDimension,
    ReferenceOnlyDimension,
    SpendToAllocate,
)
from costformation.global_dimensions import (
    BillingLineItem,
    Category,
    CommittedUseSubscription_Display,
    Elasticity,
    GenAI_Model,
    GenAI_Model_Family,
    GenAI_Model_Family_Override,
    GenAI_Model_Override,
    GenAI_Platform,
    GenAI_Platform_Override,
    GenAI_TokenType,
    InstanceType,
    NetworkingCategory,
    NetworkingCategory_VPCFlowlog,
    NetworkingSubCategory,
    PaymentOption,
    Resource_LowCardinality,
    ResourceDisplay,
    ResourceNameOnly,
    ResourceSummaryDisplay,
    ResourceSummaryID,
    ResourceSummaryID_Override,
    ResourceType,
    ResourceType_Split,
    ServiceCategory_Override,
    ServiceDetail,
    ServiceDetail_Breakdown_AWS,
    ServiceDetail_Breakdown_Azure,
    ServiceDetail_DT_InterRegion_AWS,
    ServiceDisplay,
    TaggableVsUntaggable,
)
from costformation.ref import Ref
from costformation.rules import GroupByRule, GroupRule, MetadataRule, Rule
from costformation.transforms import (
    Clean,
    Lookup,
    Lower,
    Normalize,
    Split,
    Title,
    Transform,
    Trim,
    Upper,
)

__version__ = '0.0.8'

__all__ = [
    # Conditions - Logical
    'Condition',
    'And',
    'Or',
    'Not',
    # Conditions - Equality & String
    'Equals',
    'Contains',
    'BeginsWith',
    'EndsWith',
    'Matches',
    'HasValue',
    # Conditions - Alphabetical
    'Before',
    'BeforeOrEquals',
    'After',
    'AfterOrEquals',
    # Conditions - Date
    'ForDateRange',
    # Dimensions
    'CostFormation',
    'Dimension',
    'ReferenceOnlyDimension',
    'CoreDimension',
    'GlobalDimension',
    'GroupDimension',
    'AllocationDimension',
    # Allocation building blocks
    'SpendToAllocate',
    'AcrossElements',
    'ForEachElementOf',
    'AllocationMethod',
    'ProportionalMethod',
    'Granularity',
    'CostType',
    'FixedRate',
    'ElementCutoff',
    # Core Dimensions
    'Tag',
    'K8s_Label',
    'K8s_Cluster',
    'K8s_Namespace',
    'K8s_Workload',
    'Account',
    'BillingConnectionID',
    'CloudProvider',
    'CommittedUseSubscription',
    'Description',
    'InvoiceID',
    'LineItemType',
    'Operation',
    'PayerAccount',
    'PricingTerm',
    'PricingUnit',
    'PricingUnits',
    'ProductFamily',
    'Region',
    'Resource',
    'RequestType',
    'Service',
    'TransferType',
    'UsageDay',
    'UsageFamily',
    'UsageType',
    # Global Dimensions (CloudZero-managed)
    'BillingLineItem',
    'Category',
    'CommittedUseSubscription_Display',
    'Elasticity',
    'GenAI_Model',
    'GenAI_Model_Family',
    'GenAI_Model_Family_Override',
    'GenAI_Model_Override',
    'GenAI_Platform',
    'GenAI_Platform_Override',
    'GenAI_TokenType',
    'InstanceType',
    'NetworkingCategory',
    'NetworkingCategory_VPCFlowlog',
    'NetworkingSubCategory',
    'PaymentOption',
    'Resource_LowCardinality',
    'ResourceDisplay',
    'ResourceNameOnly',
    'ResourceSummaryDisplay',
    'ResourceSummaryID',
    'ResourceSummaryID_Override',
    'ResourceType',
    'ResourceType_Split',
    'ServiceCategory_Override',
    'ServiceDetail',
    'ServiceDetail_Breakdown_AWS',
    'ServiceDetail_Breakdown_Azure',
    'ServiceDetail_DT_InterRegion_AWS',
    'ServiceDisplay',
    'TaggableVsUntaggable',
    # Rules
    'Rule',
    'GroupRule',
    'GroupByRule',
    'MetadataRule',
    # Reference (for testing)
    'Ref',
    # Transforms
    'Transform',
    'Lower',
    'Upper',
    'Title',
    'Split',
    'Trim',
    'Clean',
    'Normalize',
    'Lookup',
]
